#!/bin/bash
# This converts hole.avi to hole.amv
# by Tom
#
# NOTE !!! Make sure you've run ./srcprepare.sh and compiled ffmpeg (cd ffmpeg;./configure;make)

ffmpeg/ffmpeg -i hole.avi -f amv -intra -r 12 -vcodec mjpeg -s 160x120 -ac 1 -ar 16000 -acodec adpcm_ima_wav hole.amv

# Framerate = 8
# ffmpeg/ffmpeg -i hole.avi -f amv -intra -r 11 -vcodec mjpeg -s 160x120 -ac 1 -ar 16000 -acodec adpcm_ima_wav hole.amv

# No audio stream:
# ffmpeg/ffmpeg -i hole.avi -f amv -intra -r 16 -vcodec mjpeg -s 160x120 -an -ac 1 -ar 16000 -acodec adpcm_ima_wav hole.amv
